# Setup
title:        Harmony Boilerplate
tagline:      Multiple Database Support Express React Boilerplate
baseurl:      ""
paginate:     1

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown